"""
IL-9 Democratic Primary -- Prediction Market Trading Strategy

Binary event contract strategy engine using Kelly criterion for position sizing.
Long Simmons (underpriced), short Biss and Abughazaleh (overpriced).

Key invariant: YES_price + NO_price ~ $1.00 (minus Kalshi vig).
Going long = buy YES. Going short = buy NO.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field

from config import CANDIDATE_NAMES, SHORT_NAMES, StrategyConfig


@dataclass
class Signal:
    """A trading signal generated by the strategy."""

    ticker: str
    action: str  # "buy" or "sell"
    side: str  # "yes" or "no"
    count: int  # contracts
    limit_price: int  # cents (1-99)
    edge: float  # estimated edge (our_prob - market_prob or market_prob - our_prob)
    kelly_fraction: float
    reason: str

    def __str__(self) -> str:
        name = SHORT_NAMES.get(self.ticker, self.ticker)
        return (
            f"Signal({name}: {self.action} {self.count}x {self.side.upper()} "
            f"@ {self.limit_price}c | edge={self.edge:.1%} "
            f"kelly={self.kelly_fraction:.3f} | {self.reason})"
        )


class IL9Strategy:
    """
    Long Simmons / Short Majors strategy for IL-9 primary.

    Uses Kelly criterion for binary markets to size positions.
    Generates signals when edge exceeds slippage threshold.
    """

    def __init__(self, config: StrategyConfig | None = None) -> None:
        self.config: StrategyConfig = config or StrategyConfig()
        # ticker -> {side: "yes"|"no", count: int, avg_price: float}
        self.positions: dict[str, dict[str, str | int | float]] = {}

    # ------------------------------------------------------------------
    # Kelly sizing
    # ------------------------------------------------------------------

    def kelly_yes(self, prob: float, yes_price: float) -> float:
        """
        Kelly fraction for buying YES.

        prob: our estimated probability of YES resolving (0-1)
        yes_price: market price of YES contract (0-1)

        Returns: fraction of bankroll to wager (already scaled by kelly_scale).
                 Negative fractions clamped to 0 -- no signal, not a short.
        """
        if yes_price <= 0 or yes_price >= 1 or prob <= 0:
            return 0.0
        # Net fractional odds: win (1 - yes_price) per yes_price risked
        b: float = (1.0 - yes_price) / yes_price
        f: float = (prob * (b + 1.0) - 1.0) / b
        return max(0.0, f * self.config.kelly_scale)

    def kelly_no(self, prob_yes: float, no_price: float) -> float:
        """
        Kelly fraction for buying NO (shorting YES).

        prob_yes: our estimated probability of YES resolving (0-1)
        no_price: market price of NO contract (0-1)

        If we think YES is overpriced, we buy NO.
        Our probability of NO resolving = 1 - prob_yes.
        Positive Kelly means the NO side has edge.
        """
        prob_no: float = 1.0 - prob_yes
        if no_price <= 0 or no_price >= 1 or prob_no <= 0:
            return 0.0
        b: float = (1.0 - no_price) / no_price
        f: float = (prob_no * (b + 1.0) - 1.0) / b
        return max(0.0, f * self.config.kelly_scale)

    # ------------------------------------------------------------------
    # Core evaluation
    # ------------------------------------------------------------------

    def evaluate(self, market_prices: dict[str, dict[str, float]]) -> list[Signal]:
        """
        Evaluate all markets and generate signals.

        Args:
            market_prices: {ticker: {"yes_price": float 0-1,
                                      "no_price": float 0-1,
                                      "volume": int,
                                      "open_interest": int}}

        Returns:
            List of Signal objects for recommended trades.
        """
        signals: list[Signal] = []
        total_exposure: float = self._total_exposure()

        for ticker, target_side in self.config.target_sides.items():
            mkt = market_prices.get(ticker)
            if mkt is None:
                continue

            our_prob: float | None = self.config.prob_estimates.get(ticker)
            if our_prob is None:
                continue

            yes_price: float = mkt["yes_price"]
            no_price: float = mkt["no_price"]

            # Calculate Kelly fraction and determine trade parameters
            if target_side == "long_yes":
                kf = self.kelly_yes(our_prob, yes_price)
                trade_side = "yes"
                price_per_contract = yes_price
                edge = our_prob - yes_price
            elif target_side == "short_yes":
                kf = self.kelly_no(our_prob, no_price)
                trade_side = "no"
                price_per_contract = no_price
                edge = (1.0 - our_prob) - no_price  # prob_no - no_price
            else:
                continue

            if kf <= 0 or price_per_contract <= 0:
                continue

            # Edge too small relative to likely slippage -- skip
            if abs(edge) < price_per_contract * self.config.max_slippage_pct * 0.01:
                continue

            # Target position in contracts
            wager_dollars: float = kf * self.config.bankroll
            # Enforce per-ticker max position
            max_wager: float = self.config.max_position_pct * self.config.bankroll
            wager_dollars = min(wager_dollars, max_wager)

            # Enforce total bankroll constraint
            remaining_bankroll: float = self.config.bankroll - total_exposure
            wager_dollars = min(wager_dollars, remaining_bankroll)
            if wager_dollars <= 0:
                continue

            target_contracts: int = math.floor(wager_dollars / price_per_contract)
            if target_contracts <= 0:
                continue

            # Current position for this ticker
            current_count: int = self._position_count(ticker, trade_side)

            # Do we need to rebalance?
            delta: int = target_contracts - current_count
            if delta <= 0:
                continue

            # Only generate signal if deviation is meaningful
            if current_count > 0:
                deviation: float = abs(delta) / target_contracts
                if deviation < self.config.rebalance_threshold:
                    continue

            # Convert price to cents for the limit order
            limit_cents: int = max(1, min(99, round(price_per_contract * 100)))

            name = CANDIDATE_NAMES.get(ticker, ticker)
            if target_side == "long_yes":
                reason = (
                    f"Long {name}: our prob {our_prob:.0%} vs market "
                    f"{yes_price:.0%} -- underpriced"
                )
            else:
                reason = (
                    f"Short {name}: our prob {our_prob:.0%} vs market "
                    f"{yes_price:.0%} -- overpriced"
                )

            signal = Signal(
                ticker=ticker,
                action="buy",
                side=trade_side,
                count=delta,
                limit_price=limit_cents,
                edge=edge,
                kelly_fraction=kf,
                reason=reason,
            )
            signals.append(signal)

            # Optimistically book exposure so subsequent tickers respect limits
            total_exposure += delta * price_per_contract

        return signals

    # ------------------------------------------------------------------
    # Position management
    # ------------------------------------------------------------------

    def update_positions(self, positions: list[dict[str, str | int | float]]) -> None:
        """
        Update internal position state from broker data.

        Each dict should have:
            ticker: str
            side: "yes" | "no"
            count: int
            avg_price: float (0-1)
        """
        self.positions.clear()
        for pos in positions:
            ticker = str(pos["ticker"])
            self.positions[ticker] = {
                "side": str(pos["side"]),
                "count": int(pos["count"]),  # type: ignore[arg-type]
                "avg_price": float(pos["avg_price"]),  # type: ignore[arg-type]
            }

    def _position_count(self, ticker: str, side: str) -> int:
        """Get current contract count for a ticker on a given side."""
        pos = self.positions.get(ticker)
        if pos is None:
            return 0
        if pos["side"] != side:
            return 0
        return int(pos["count"])  # type: ignore[arg-type]

    def _total_exposure(self) -> float:
        """Total dollar exposure across all positions."""
        total: float = 0.0
        for pos in self.positions.values():
            count = int(pos["count"])  # type: ignore[arg-type]
            avg_price = float(pos["avg_price"])  # type: ignore[arg-type]
            total += count * avg_price
        return total

    def net_exposure(self) -> float:
        """Calculate total $ exposure across all positions."""
        return self._total_exposure()

    def portfolio_summary(self) -> dict[str, object]:
        """
        Return current portfolio state:
        - positions by ticker
        - total exposure
        - remaining bankroll
        - unrealized P&L estimates
        """
        exposure: float = self._total_exposure()
        pos_details: dict[str, dict[str, object]] = {}

        for ticker, pos in self.positions.items():
            name = CANDIDATE_NAMES.get(ticker, ticker)
            short = SHORT_NAMES.get(ticker, ticker)
            count = int(pos["count"])  # type: ignore[arg-type]
            avg_price = float(pos["avg_price"])  # type: ignore[arg-type]
            cost_basis: float = count * avg_price

            pos_details[short] = {
                "name": name,
                "side": pos["side"],
                "count": count,
                "avg_price": avg_price,
                "cost_basis": round(cost_basis, 2),
            }

        return {
            "positions": pos_details,
            "total_exposure": round(exposure, 2),
            "remaining_bankroll": round(self.config.bankroll - exposure, 2),
            "bankroll": self.config.bankroll,
        }


# ======================================================================
# Demo
# ======================================================================


def _print_section(title: str) -> None:
    print(f"\n{'=' * 60}")
    print(f"  {title}")
    print(f"{'=' * 60}")


if __name__ == "__main__":
    config = StrategyConfig()
    strategy = IL9Strategy(config)

    # ------------------------------------------------------------------
    # Sample market prices (approx current Kalshi levels)
    # ------------------------------------------------------------------
    market_prices: dict[str, dict[str, float]] = {
        "KXIL9D-26-MSIM": {
            "yes_price": 0.01,
            "no_price": 0.99,
            "volume": 0,
            "open_interest": 0,
        },
        "KXIL9D-26-DBIS": {
            "yes_price": 0.68,
            "no_price": 0.32,
            "volume": 50,
            "open_interest": 100,
        },
        "KXIL9D-26-KA": {
            "yes_price": 0.31,
            "no_price": 0.69,
            "volume": 25,
            "open_interest": 50,
        },
    }

    _print_section("IL-9 Strategy Engine -- Kelly Analysis")

    print(f"\nBankroll:      ${config.bankroll:.2f}")
    print(f"Kelly scale:   {config.kelly_scale:.0%} (quarter-Kelly)")
    print(f"Max position:  {config.max_position_pct:.0%} of bankroll")

    # ------------------------------------------------------------------
    # Kelly fractions for each target
    # ------------------------------------------------------------------
    _print_section("Kelly Fractions")

    for ticker, side in config.target_sides.items():
        mkt = market_prices.get(ticker)
        if mkt is None:
            continue

        our_prob = config.prob_estimates[ticker]
        yes_p = mkt["yes_price"]
        no_p = mkt["no_price"]
        name = SHORT_NAMES.get(ticker, ticker)

        if side == "long_yes":
            kf = strategy.kelly_yes(our_prob, yes_p)
            edge = our_prob - yes_p
            print(f"\n  {name} (LONG YES):")
            print(f"    Our prob:     {our_prob:.0%}")
            print(f"    YES price:    {yes_p:.0%}")
            print(f"    Edge:         {edge:+.1%}")
            print(f"    Full Kelly:   {kf / config.kelly_scale:.3f}")
            print(f"    Quarter-Kelly:{kf:.3f}")
            wager = kf * config.bankroll
            contracts = math.floor(wager / yes_p)
            print(f"    Wager:        ${wager:.2f}")
            print(f"    Contracts:    {contracts} YES @ {round(yes_p * 100)}c")
        else:
            kf = strategy.kelly_no(our_prob, no_p)
            edge = (1.0 - our_prob) - no_p
            print(f"\n  {name} (SHORT YES / BUY NO):")
            print(f"    Our YES prob: {our_prob:.0%}")
            print(f"    NO price:     {no_p:.0%}")
            print(f"    Edge:         {edge:+.1%}")
            print(f"    Full Kelly:   {kf / config.kelly_scale:.3f}")
            print(f"    Quarter-Kelly:{kf:.3f}")
            wager = kf * config.bankroll
            contracts = math.floor(wager / no_p)
            print(f"    Wager:        ${wager:.2f}")
            print(f"    Contracts:    {contracts} NO @ {round(no_p * 100)}c")

    # ------------------------------------------------------------------
    # Generate signals (no existing positions)
    # ------------------------------------------------------------------
    _print_section("Generated Signals (fresh portfolio)")

    signals = strategy.evaluate(market_prices)
    if not signals:
        print("\n  No signals generated.")
    else:
        for sig in signals:
            print(f"\n  {sig}")

    # ------------------------------------------------------------------
    # Simulate filling signals and show portfolio
    # ------------------------------------------------------------------
    _print_section("Portfolio After Fills")

    filled_positions: list[dict[str, str | int | float]] = []
    for sig in signals:
        filled_positions.append(
            {
                "ticker": sig.ticker,
                "side": sig.side,
                "count": sig.count,
                "avg_price": sig.limit_price / 100.0,
            }
        )
    strategy.update_positions(filled_positions)

    summary = strategy.portfolio_summary()
    print(f"\n  Total exposure:     ${summary['total_exposure']}")
    print(f"  Remaining bankroll: ${summary['remaining_bankroll']}")
    print(f"  Positions:")
    positions_dict: dict[str, dict[str, object]] = summary["positions"]  # type: ignore[assignment]
    for short_name, details in positions_dict.items():
        print(
            f"    {short_name}: {details['count']}x {details['side']} "
            f"@ {details['avg_price']} "
            f"(cost ${details['cost_basis']})"
        )

    # ------------------------------------------------------------------
    # Re-evaluate with positions -- should produce no signals
    # ------------------------------------------------------------------
    _print_section("Re-evaluation (with positions)")

    signals_after = strategy.evaluate(market_prices)
    if not signals_after:
        print("\n  No new signals -- positions are on target.")
    else:
        for sig in signals_after:
            print(f"\n  {sig}")
